//
//  PostsPresenter.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostsPresenter {

    // MARK: - Private properties -

    private unowned let view: PostsViewInterface
    private let interactor: PostsInteractorInterface
    private let wireframe: PostsWireframeInterface

    // MARK: - Lifecycle -

    init(view: PostsViewInterface, interactor: PostsInteractorInterface, wireframe: PostsWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PostsPresenter: PostsPresenterInterface {
    func viewDidLoad() {
        
    }
}
