//
//  PostsInteractor.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostsInteractor {
    private let dataProvider: PostDataProviderInterface
    weak var output: PostsInteractorOutputInterface!
    
    init(dataProvider: PostDataProviderInterface) {
        self.dataProvider = dataProvider
    }
}

// MARK: - Extensions -

extension PostsInteractor: PostsInteractorInputInterface {
    func getPosts() {
        dataProvider.fetchPosts(completion: { [weak self] _ in
            self?.output.postsReceived()
        })
    }
    
    func getNumberOfItems() -> Int {
        return dataProvider.currentPosts.count
    }
    
    func getItem(at index: Int) -> PostViewModelProtocol {
        return dataProvider.currentPosts[index]
    }
    
    func getDataProvider() -> PostDataProviderInterface {
        return dataProvider
    }
    
    func getCommentRequest(for index: Int) -> CommentRequest {
        let post = getItem(at: index)
        return CommentRequest(postID: post.postID)
    }
}
