//
//  PostsWireframe.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostsWireframe: BaseWireframe {

    // MARK: - Module setup -
    
    init() {
        let moduleViewController = PostsViewController.loadFromNib()
        super.init(viewController: moduleViewController)

        let apiResponseHandler = APIResponseHandler()
        let apiErrorHandler = APIErrorHandler()
        let apiLayer = APILayer(apiResponseHandler: apiResponseHandler)
        
        let persistenceLayer = CoreDataStack()
        let dataStore = PostDataStore()
        
        let dataProvider = PostDataProvider(apiLayer: apiLayer,
                                        apiResponseHandler: apiResponseHandler,
                                        apiErrorHandler: apiErrorHandler,
                                        persistenceLayerOutput: persistenceLayer,
                                        persistenceLayerInput: persistenceLayer,
                                        dataStore: dataStore)
        
        let interactor = PostsInteractor(dataProvider: dataProvider)
        
        let presenter = PostsPresenter(view: moduleViewController,
                                       interactor: interactor,
                                       dataStore: dataStore,
                                       wireframe: self)
        
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PostsWireframe: PostsWireframeInterface {
}
