//
//  PostsPresenter.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostsPresenter {

    // MARK: - Private properties -

    private unowned let view: PostsViewInterface
    private let interactor: PostsInteractorInputInterface
    private let router: PostsRouterInterface
    
    // MARK: - Lifecycle -

    init(view: PostsViewInterface,
         interactor: PostsInteractorInputInterface,
         router: PostsRouterInterface) {
        
        self.view = view
        self.interactor = interactor
        self.router = router
    }
}

// MARK: - Extensions -

extension PostsPresenter: PostsPresenterInterface {
    func viewDidLoad() {
        view.showProgressHUD()
        interactor.getPosts()
    }
    
    func numberOfItems() -> Int {
        return interactor.getNumberOfItems()
    }
    
    func item(at index: Int) -> PostTableCellViewModelProtocol {
        let post = interactor.getItem(at: index)
        return PostTableCellViewModel(title: post.title)
    }
    
    func didSelectItem(at index: Int) {
        let dataProvider = interactor.getDataProvider()
        let post = interactor.getItem(at: index)
        router.navigateToPostDetail(with: dataProvider, postID: post.postID)
    }
}

extension PostsPresenter: PostsInteractorOutputInterface {
    func postsReceived() {
        view.hideProgressHUD()
        view.reloadInterface()
    }
}
