//
//  PostsInteractor.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostsInteractor {
    private let dataProvider: PostDataProviderInterface
    
    init(dataProvider: PostDataProviderInterface) {
        self.dataProvider = dataProvider
    }
}

// MARK: - Extensions -

extension PostsInteractor: PostsInteractorInterface {
    func getPosts(completion: @escaping ([PostViewModelProtocol]) -> Void) {
        dataProvider.getPosts(completion: completion)
    }
}
