//
//  PostsWireframe.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostsWireframe: BaseWireframe {

    // MARK: - Module setup -
    
    init() {
        let moduleViewController = PostsViewController.loadFromNib()
        super.init(viewController: moduleViewController)

        let interactor = PostsInteractor()
        let presenter = PostsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PostsWireframe: PostsWireframeInterface {
}
