//
//  PostDetailInterfaces.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PostDetailWireframeInterface: WireframeInterface {
    static func assembleWireframe(with dataProvider: PostDataProviderInterface, postID: Int) -> PostDetailWireframe
}

protocol PostDetailRouterInterface: RouterInterface {
    func navigateToBack()
}

protocol PostDetailViewInterface: ViewInterface {
    func reloadInterface()
}

protocol PostDetailPresenterInterface: PresenterInterface {}

protocol PostDetailInteractorInputInterface: InteractorInterface {
    func getComments(for postID: Int)
}

protocol PostDetailInteractorOutputInterface: InteractorInterface {
    func commentsReceived(comments: [CommentViewModelProtocol])
}

