//
//  PostDetailViewController.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostDetailViewController: UIViewController {

    @IBOutlet private weak var tableView: UITableView!
    
    // MARK: - Public properties -

    var presenter: PostDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        presenter.viewDidLoad()
    }
}

// MARK: - Extensions -

extension PostDetailViewController: PostDetailViewInterface {
    func reloadInterface() {
        
    }
}
