//
//  PostDetailInterfaces.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PostDetailWireframeInterface: WireframeInterface {
    static func assembleWireframe(with dataProvider: PostDataProviderInterface, post: PostViewModelProtocol) -> PostDetailWireframe
}

protocol PostDetailRouterInterface: RouterInterface {
    func navigateToBack()
}

protocol PostDetailViewInterface: ViewInterface {
    func setTitle(_ title: String)
    func reloadInterface()
}

protocol PostDetailPresenterInterface: PresenterInterface {
    func numberOfSections() -> Int
    func numberOfItems(in section: Int) -> Int
    func item(at section: Int, row: Int) -> MultiPurposeTableCellViewModelable
}

protocol PostDetailInteractorInputInterface: InteractorInterface {
    func getComments(for post: PostViewModelProtocol)
}

protocol PostDetailInteractorOutputInterface: InteractorInterface {
    func commentsReceived(comments: [CommentViewModelProtocol])
}

