//
//  PostDetailInteractor.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostDetailInteractor {
}

// MARK: - Extensions -

extension PostDetailInteractor: PostDetailInteractorInterface {
}
