//
//  PostDetailInterfaces.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol PostDetailWireframeInterface: WireframeInterface {
}

protocol PostDetailViewInterface: ViewInterface {
}

protocol PostDetailPresenterInterface: PresenterInterface {
}

protocol PostDetailInteractorInterface: InteractorInterface {
}
