//
//  PostDetailInteractor.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PostDetailInteractor {
    private let dataProvider: PostDataProviderInterface
    weak var output: PostDetailInteractorOutputInterface!
    
    init(dataProvider: PostDataProviderInterface) {
        self.dataProvider = dataProvider
    }
}

// MARK: - Extensions -

extension PostDetailInteractor: PostDetailInteractorInputInterface {
    func getComments(for postID: Int) {
        dataProvider.fetchComments(for: postID) { [weak self] comments in
            self?.output.commentsReceived(comments: comments)
        }
    }
}
