//
//  PostDetailWireframe.swift
//  SocialMedia
//
//  Created by Okhan Okbay on 26.12.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PostDetailWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = PostDetailViewController()
        super.init(viewController: moduleViewController)

        let interactor = PostDetailInteractor()
        let presenter = PostDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PostDetailWireframe: PostDetailWireframeInterface {
}
